<?php
/**
 * Trí Đức theme.
 *
 * The pages are the website's React app (app/, built by wordpress/build.ts from the main project); this PHP
 * side gives it WordPress content and does what the static hosting did at build time:
 *   inc/content.php   post types (Sản phẩm, Tài liệu, Tuyển dụng, Khách liên hệ), news categories, the site's URLs
 *   inc/data.php      the content handed to the app (window.__TD__, see src/wp.ts in the project)
 *   inc/seo.php       per-page title, meta tags, structured data and the plain-HTML copy crawlers read
 *   inc/frontend.php  routing: old-URL redirects, the app's pages, the data/form/chat endpoints, theme images
 *   inc/ai.php        what the AI chat knows (api/chat.php), built from the WordPress content
 *   inc/sitemap.php   the app's own pages in wp-sitemap.xml
 *   inc/admin.php     product/SEO fields in the editor, the "Trí Đức" settings screen, the enquiries list
 * data/*.json are generated by the build from the project (brands, buying guides, page texts, form labels).
 */

defined('ABSPATH') || exit;

define('TD_DIR', __DIR__);
define('TD_VERSION', (string) wp_get_theme(get_template())->get('Version'));

require TD_DIR . '/inc/content.php';
require TD_DIR . '/inc/data.php';
require TD_DIR . '/inc/seo.php';
require TD_DIR . '/inc/frontend.php';
require TD_DIR . '/inc/ai.php';
require TD_DIR . '/inc/sitemap.php';

if (is_admin()) {
    require TD_DIR . '/inc/admin.php';
}
